/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopAccountRouteImport } from './routes/shop.account'
import { Route as ShopCartRouteImport } from './routes/shop.cart'
import { Route as ShopSearchRouteImport } from './routes/shop.search'
import { Route as ShopAccountIndexRouteImport } from './routes/shop.account.index'
import { Route as ShopAccountAddressesRouteImport } from './routes/shop.account.addresses'
import { Route as ShopAccountCallbackRouteImport } from './routes/shop.account.callback'
import { Route as ShopAccountLoginRouteImport } from './routes/shop.account.login'
import { Route as ShopAccountLogoutRouteImport } from './routes/shop.account.logout'
import { Route as ShopAccountOrdersRouteImport } from './routes/shop.account.orders'
import { Route as ShopCollectionsHandleRouteImport } from './routes/shop.collections.$handle'
import { Route as ShopPagesHandleRouteImport } from './routes/shop.pages.$handle'
import { Route as ShopPoliciesHandleRouteImport } from './routes/shop.policies.$handle'
import { Route as ShopProductsHandleRouteImport } from './routes/shop.products.$handle'
import { Route as ShopAccountOrdersIdRouteImport } from './routes/shop.account.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSearchRoute = ShopSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountIndexRoute = ShopAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountAddressesRoute = ShopAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountCallbackRoute = ShopAccountCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountLoginRoute = ShopAccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountLogoutRoute = ShopAccountLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopAccountOrdersRoute = ShopAccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopAccountRoute,
} as any)
const ShopCollectionsHandleRoute = ShopCollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPagesHandleRoute = ShopPagesHandleRouteImport.update({
  id: '/pages/$handle',
  path: '/pages/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPoliciesHandleRoute = ShopPoliciesHandleRouteImport.update({
  id: '/policies/$handle',
  path: '/policies/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsHandleRoute = ShopProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountOrdersIdRoute = ShopAccountOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopAccountOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/shop/account': typeof ShopAccountRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/callback': typeof ShopAccountCallbackRoute
  '/shop/account/login': typeof ShopAccountLoginRoute
  '/shop/account/logout': typeof ShopAccountLogoutRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
  '/shop/account/': typeof ShopAccountIndexRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop': typeof ShopIndexRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/callback': typeof ShopAccountCallbackRoute
  '/shop/account/login': typeof ShopAccountLoginRoute
  '/shop/account/logout': typeof ShopAccountLogoutRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
  '/shop/account': typeof ShopAccountIndexRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRouteWithChildren
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/shop/account': typeof ShopAccountRouteWithChildren
  '/shop/cart': typeof ShopCartRoute
  '/shop/search': typeof ShopSearchRoute
  '/shop/': typeof ShopIndexRoute
  '/shop/account/addresses': typeof ShopAccountAddressesRoute
  '/shop/account/callback': typeof ShopAccountCallbackRoute
  '/shop/account/login': typeof ShopAccountLoginRoute
  '/shop/account/logout': typeof ShopAccountLogoutRoute
  '/shop/account/orders': typeof ShopAccountOrdersRouteWithChildren
  '/shop/collections/$handle': typeof ShopCollectionsHandleRoute
  '/shop/pages/$handle': typeof ShopPagesHandleRoute
  '/shop/policies/$handle': typeof ShopPoliciesHandleRoute
  '/shop/products/$handle': typeof ShopProductsHandleRoute
  '/shop/account/': typeof ShopAccountIndexRoute
  '/shop/account/orders/$id': typeof ShopAccountOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/shop'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/shop/account/addresses'
    | '/shop/account/callback'
    | '/shop/account/login'
    | '/shop/account/logout'
    | '/shop/account/orders'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
    | '/shop/account/'
    | '/shop/account/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/shop/cart'
    | '/shop/search'
    | '/shop'
    | '/shop/account/addresses'
    | '/shop/account/callback'
    | '/shop/account/login'
    | '/shop/account/logout'
    | '/shop/account/orders'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
    | '/shop/account'
    | '/shop/account/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/shop'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/shop/account'
    | '/shop/cart'
    | '/shop/search'
    | '/shop/'
    | '/shop/account/addresses'
    | '/shop/account/callback'
    | '/shop/account/login'
    | '/shop/account/logout'
    | '/shop/account/orders'
    | '/shop/collections/$handle'
    | '/shop/pages/$handle'
    | '/shop/policies/$handle'
    | '/shop/products/$handle'
    | '/shop/account/'
    | '/shop/account/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ShopRoute: typeof ShopRouteWithChildren
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account': {
      id: '/shop/account'
      path: '/account'
      fullPath: '/shop/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/cart': {
      id: '/shop/cart'
      path: '/cart'
      fullPath: '/shop/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/search': {
      id: '/shop/search'
      path: '/search'
      fullPath: '/shop/search'
      preLoaderRoute: typeof ShopSearchRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account/': {
      id: '/shop/account/'
      path: '/'
      fullPath: '/shop/account/'
      preLoaderRoute: typeof ShopAccountIndexRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/addresses': {
      id: '/shop/account/addresses'
      path: '/addresses'
      fullPath: '/shop/account/addresses'
      preLoaderRoute: typeof ShopAccountAddressesRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/callback': {
      id: '/shop/account/callback'
      path: '/callback'
      fullPath: '/shop/account/callback'
      preLoaderRoute: typeof ShopAccountCallbackRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/login': {
      id: '/shop/account/login'
      path: '/login'
      fullPath: '/shop/account/login'
      preLoaderRoute: typeof ShopAccountLoginRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/logout': {
      id: '/shop/account/logout'
      path: '/logout'
      fullPath: '/shop/account/logout'
      preLoaderRoute: typeof ShopAccountLogoutRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/account/orders': {
      id: '/shop/account/orders'
      path: '/orders'
      fullPath: '/shop/account/orders'
      preLoaderRoute: typeof ShopAccountOrdersRouteImport
      parentRoute: typeof ShopAccountRoute
    }
    '/shop/collections/$handle': {
      id: '/shop/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/shop/collections/$handle'
      preLoaderRoute: typeof ShopCollectionsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/pages/$handle': {
      id: '/shop/pages/$handle'
      path: '/pages/$handle'
      fullPath: '/shop/pages/$handle'
      preLoaderRoute: typeof ShopPagesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/policies/$handle': {
      id: '/shop/policies/$handle'
      path: '/policies/$handle'
      fullPath: '/shop/policies/$handle'
      preLoaderRoute: typeof ShopPoliciesHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/products/$handle': {
      id: '/shop/products/$handle'
      path: '/products/$handle'
      fullPath: '/shop/products/$handle'
      preLoaderRoute: typeof ShopProductsHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/account/orders/$id': {
      id: '/shop/account/orders/$id'
      path: '/$id'
      fullPath: '/shop/account/orders/$id'
      preLoaderRoute: typeof ShopAccountOrdersIdRouteImport
      parentRoute: typeof ShopAccountOrdersRoute
    }
  }
}

interface ShopAccountOrdersRouteChildren {
  ShopAccountOrdersIdRoute: typeof ShopAccountOrdersIdRoute
}

const ShopAccountOrdersRouteChildren: ShopAccountOrdersRouteChildren = {
  ShopAccountOrdersIdRoute: ShopAccountOrdersIdRoute,
}

const ShopAccountOrdersRouteWithChildren =
  ShopAccountOrdersRoute._addFileChildren(ShopAccountOrdersRouteChildren)

interface ShopAccountRouteChildren {
  ShopAccountAddressesRoute: typeof ShopAccountAddressesRoute
  ShopAccountCallbackRoute: typeof ShopAccountCallbackRoute
  ShopAccountLoginRoute: typeof ShopAccountLoginRoute
  ShopAccountLogoutRoute: typeof ShopAccountLogoutRoute
  ShopAccountOrdersRoute: typeof ShopAccountOrdersRouteWithChildren
  ShopAccountIndexRoute: typeof ShopAccountIndexRoute
}

const ShopAccountRouteChildren: ShopAccountRouteChildren = {
  ShopAccountAddressesRoute: ShopAccountAddressesRoute,
  ShopAccountCallbackRoute: ShopAccountCallbackRoute,
  ShopAccountLoginRoute: ShopAccountLoginRoute,
  ShopAccountLogoutRoute: ShopAccountLogoutRoute,
  ShopAccountOrdersRoute: ShopAccountOrdersRouteWithChildren,
  ShopAccountIndexRoute: ShopAccountIndexRoute,
}

const ShopAccountRouteWithChildren = ShopAccountRoute._addFileChildren(
  ShopAccountRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRouteWithChildren
  ShopCartRoute: typeof ShopCartRoute
  ShopSearchRoute: typeof ShopSearchRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCollectionsHandleRoute: typeof ShopCollectionsHandleRoute
  ShopPagesHandleRoute: typeof ShopPagesHandleRoute
  ShopPoliciesHandleRoute: typeof ShopPoliciesHandleRoute
  ShopProductsHandleRoute: typeof ShopProductsHandleRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRouteWithChildren,
  ShopCartRoute: ShopCartRoute,
  ShopSearchRoute: ShopSearchRoute,
  ShopIndexRoute: ShopIndexRoute,
  ShopCollectionsHandleRoute: ShopCollectionsHandleRoute,
  ShopPagesHandleRoute: ShopPagesHandleRoute,
  ShopPoliciesHandleRoute: ShopPoliciesHandleRoute,
  ShopProductsHandleRoute: ShopProductsHandleRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ShopRoute: ShopRouteWithChildren,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
